name: chat_gh
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  google_sign_in: ^5.0.0
  shared_preferences: ^2.0.3
  random_string: ^2.1.0
  cloud_firestore: ^1.0.1
  curved_navigation_bar: ^0.3.7
  http: ^0.13.0
  rxdart: ^0.18.0
  font_awesome_flutter: ^9.0.0
  rflutter_alert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  iso: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "JustAsk"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
